[build]
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow, noarchive"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), payment=(self)"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Cross-Origin-Opener-Policy = "same-origin-allow-popups"